# Generated by Django 2.2 on 2022-09-09 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carid',
            new_name='carname',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='carnumber',
        ),
        migrations.AddField(
            model_name='car',
            name='carcolor',
            field=models.CharField(default='NOCOLOR', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='carowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='registereddate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
