# Generated by Django 2.2 on 2022-09-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('PARKED', 'Parked'), ('UNPARKED', 'Unparked')], default='UNPARKED', max_length=20),
        ),
    ]
