# Generated by Django 2.2 on 2022-09-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0002_auto_20220917_1231'),
        ('carapp', '0004_auto_20220917_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.CarService')),
            ],
        ),
    ]
