# Generated by Django 2.2 on 2022-09-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_cargroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cargroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carapp.CarGroup'),
        ),
    ]
