# Generated by Django 2.2 on 2022-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MANTAINENCE', 'Mantainence')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
