# Generated by Django 2.2 on 2022-09-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='servicename',
            field=models.CharField(default='SERVICE', max_length=100),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='carmantainence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='carparking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='carsecurity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='carwash',
            field=models.BooleanField(default=False),
        ),
    ]
