# Generated by Django 2.2 on 2022-09-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caruser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarService',
        ),
    ]
